### ISSUE TITLE
Roadmap for adding new metrics 

### ISSUE THREAD

**Issue by amunz** [apache/kibble-1#12]
Hi,
@jlrifer and I plan on contributing a new metric to Kibble in the coming months. Is there an existing roadmap for contributing a new metric to Kibble? Also, are there any metrics that the community is looking to add? 

Thanks, 
Adam

**Comment by Humbedooh** [comment]
I think this is perhaps better discussed on the mailing list, but I won't dissuade you from using GitHub if that's what you feel most at home doing :) Should you decide to bring it to the lists, you can use our Pony Mail service to view/reply/subscribe at https://lists.apache.org/list.html?dev@kibble.apache.org

Having said that, the discussion is in a bit of a hiatus for the next week or two due to other engagements at Apache taking up a great deal of time for the core contributors...so it might be a while before we get a proper discussion going. But you are of course very welcome to propose items.

I have some other folks elsewhere also interested in contributing, so it would be a great idea to start getting a new road map down on paper somewhere. If you can gather whatever proposals, questions, ponderings and ideas you have and post them either here or (preferably) on the mailing list, that would be awesome :) Perhaps then we can start to formulate an intermediate roadmap for the immediate future.
